import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import StyledComponentsRegistry from '@/lib/registry'
import { PageContainer, MainContentContainer } from '@/styles/mainContentContainer'
import Header from '@/components/header'
import Footer from '@/components/footer'
import SideBar from '@/components/sidebar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <StyledComponentsRegistry>
        <body className={inter.className}>
          <PageContainer>
            <Header/>
            <MainContentContainer>
              <SideBar/>
              {children}
            </MainContentContainer>
            <Footer />
          </PageContainer>
        </body>
      </StyledComponentsRegistry>
    </html>
  )
}
